// Wayfinder Route Engine
//
// A route is a sequence of legal state transitions: CURRENT STATE → entry
// status → PR → citizenship. Routes are generated by deterministic graph
// search over the curated pathways + their downstream transitions. The LLM
// never invents route sequences; it only explains the ones produced here.
//
// TEMPORAL: generateRoutes accepts an optional asOfDate. When provided, the
// policy engine resolves the active policy snapshot for that date and swaps
// in superseded requirements (e.g. the 2026 Blue Card salary threshold when
// asOfDate >= 2026-01-01). When omitted, the current snapshot is used.

import type {
  CountryCode,
  Intent,
  MobilityState,
  Pathway,
  Requirement,
  Route,
  RouteScores,
  RouteStep,
} from '@/lib/domain/types'
import { PATHWAYS, getPathway } from '@/lib/knowledge/pathways'
import { getCountry } from '@/lib/knowledge/countries'
import { evaluatePathway, isShortage } from './policy'
import { POLICY_VERSION } from '@/lib/knowledge/policy-version'
import { getPolicySnapshot } from '@/lib/policy/snapshot'
import { getNormalizedRequirementsForPathway } from '@/lib/policy/normalize'
import type { NormalizedRequirement } from '@/lib/policy/types'

// ---------------------------------------------------------------------------
// Step construction
// ---------------------------------------------------------------------------

function buildSteps(pathway: Pathway, eligibility: ReturnType<typeof evaluatePathway>): {
  steps: RouteStep[]
  totalMonths: number
  thirdPartyDependencies: number
  reversible: boolean
  futureOptions: string[]
} {
  const steps: RouteStep[] = []
  const blockedSet = new Set(eligibility.blockers.map((b) => b.requirementId))

  // Step 0: current state
  steps.push({
    order: 0,
    status: 'Current state',
    description: `Apply for ${pathway.name} from your current country.`,
    durationMonths: pathway.processingTimeMonths,
    conditions: pathway.requirements.map((r) => r.label),
    evidenceIds: pathway.evidenceIds,
    blocked: false,
  })

  // Step 1: entry status (the pathway itself)
  const entryBlockers = pathway.requirements.filter((r) => blockedSet.has(r.id))
  steps.push({
    order: 1,
    status: pathway.name,
    description: pathway.tagline,
    durationMonths: pathway.validityMonths || pathway.processingTimeMonths,
    conditions: pathway.requirements.map((r) => r.label),
    evidenceIds: pathway.evidenceIds,
    blocked: entryBlockers.length > 0,
    blockerLabels: entryBlockers.map((r) => r.label),
  })

  // Downstream transitions
  let totalMonths = pathway.processingTimeMonths
  let reversible = pathway.downstream.every((t) => t.reversible) || pathway.downstream.length === 0
  const futureOptions: string[] = []

  pathway.downstream.forEach((t, i) => {
    steps.push({
      order: 2 + i,
      status: t.to,
      description: `${t.from} → ${t.to}`,
      durationMonths: t.durationMonths,
      conditions: t.conditions,
      evidenceIds: t.evidenceIds,
      blocked: false,
    })
    totalMonths += t.durationMonths
    if (!t.reversible) reversible = false
    futureOptions.push(t.to)
  })

  const thirdPartyDependencies = pathway.requiresThirdParty ? 1 : 0

  return { steps, totalMonths, thirdPartyDependencies, reversible, futureOptions }
}

// ---------------------------------------------------------------------------
// Scoring — multi-dimensional, never collapsed to one number for the frontier
// ---------------------------------------------------------------------------

const COUNTRY_INCOME_INDEX: Record<string, number> = {
  DE: 88, CA: 85, UK: 86, AE: 90, PT: 62, EE: 70, KE: 45,
}

function clamp(n: number, lo = 0, hi = 100) {
  return Math.max(lo, Math.min(hi, Math.round(n)))
}

function scoreRoute(
  state: MobilityState,
  intent: Intent,
  pathway: Pathway,
  eligibility: ReturnType<typeof evaluatePathway>,
  totalMonths: number,
  thirdPartyDependencies: number,
  reversible: boolean,
): RouteScores {
  const dest = getCountry(pathway.countryCode)
  const origin = getCountry(state.currentCountry.value) ?? getCountry('KE')!
  const curIncome = state.annualIncomeUSD.value ?? 40000

  // economicUpside: destination earning index vs current income
  const destIncomeIdx = COUNTRY_INCOME_INDEX[pathway.countryCode] ?? 60
  const incomeMultiple = destIncomeIdx / (COUNTRY_INCOME_INDEX[state.currentCountry.value] ?? 50)
  const economicUpside = clamp((incomeMultiple - 1) * 80 + 30 + (pathway.countryCode === 'AE' ? 12 : 0))

  // immigrationProbability: from eligibility status + dependency count + unknowns
  let prob = 75
  if (eligibility.status === 'eligible') prob = 88
  else if (eligibility.status === 'conditional') prob = 58 - eligibility.unknown.length * 6
  else prob = 18
  prob -= thirdPartyDependencies * 8
  prob -= eligibility.blockers.length * 3
  if (pathway.shortageOccupationFriendly && isShortage(state.occupationCategory.value, pathway.countryCode)) prob += 6
  const immigrationProbability = clamp(prob)

  // speed: inverse of months to PR-equivalent (cap 120 months)
  const prMonths = pathway.downstream.find((t) => /permanent|Settlement|ILR/i.test(t.to))?.durationMonths
  const monthsToDest = (prMonths ?? totalMonths) + pathway.processingTimeMonths
  const speed = clamp(100 - (monthsToDest / 120) * 100)

  // affordability: inverse of cost + capital required
  const cost = pathway.estimatedCostUSD
  const fundsReq = (pathway.requirements.find((r) => r.kind === 'min_savings_usd' || r.kind === 'settlement_funds_usd')?.params as any)?.amount ?? 0
  const totalBurden = cost + fundsReq * 0.15
  const affordability = clamp(100 - (totalBurden / 30000) * 100)

  // longTermResidence: leads to PR?
  const hasPR = pathway.downstream.some((t) => /permanent|Settlement|ILR/i.test(t.to))
  const longTermResidence = clamp(hasPR ? 88 : 35)

  // citizenshipProspect
  const hasCit = pathway.downstream.some((t) => /citizenship/i.test(t.to))
  let cit = hasCit ? 70 : 10
  if (dest?.dualCitizenship === 'permitted') cit += 12
  else if (dest?.dualCitizenship === 'restricted') cit -= 8
  else if (dest?.dualCitizenship === 'prohibited') cit -= 25
  // faster citizenship = higher
  const citMonths = pathway.downstream.find((t) => /citizenship/i.test(t.to))?.durationMonths ?? 999
  cit += clamp(20 - citMonths / 12, -10, 20)
  const citizenshipProspect = clamp(cit)

  // familyUtility
  const family = (state.hasSpouse.value === true || state.hasChildren.value === true)
  let fam = pathway.countryCode === 'CA' ? 90 : pathway.countryCode === 'PT' ? 80 : pathway.countryCode === 'DE' ? 78 : 60
  if (!family) fam = Math.min(100, fam + 8)
  const familyUtility = clamp(fam)

  // mobilityUpside: passport strength gained
  const originScore = origin.passportMobilityScore
  const destScore = dest?.passportMobilityScore ?? 70
  const mobilityUpside = clamp(((destScore - originScore) / 60) * 100 + 20)

  // optionality: future doors = downstream count + dual citizenship + EU access
  let opt = pathway.downstream.length * 12
  if (dest?.region === 'EU' || dest?.region === 'EEA') opt += 18
  if (dest?.dualCitizenship === 'permitted') opt += 10
  const optionality = clamp(opt)

  // reversibility
  const reversibility = clamp(reversible ? 80 : 30)

  // risk band
  let riskScore = 60
  if (eligibility.status === 'eligible') riskScore += 20
  else if (eligibility.status === 'ineligible') riskScore -= 35
  riskScore -= thirdPartyDependencies * 6
  riskScore -= eligibility.blockers.length * 2
  if (pathway.riskNotes?.match(/long|backlog|competitive/i)) riskScore -= 8
  const riskAdjusted = clamp(riskScore)

  return {
    economicUpside,
    immigrationProbability,
    speed,
    affordability,
    longTermResidence,
    citizenshipProspect,
    familyUtility,
    mobilityUpside,
    optionality,
    reversibility,
    riskAdjusted,
  }
}

function riskBand(scores: RouteScores, eligibility: ReturnType<typeof evaluatePathway>): Route['risk'] {
  if (eligibility.status === 'ineligible') return 'high'
  if (scores.riskAdjusted < 45) return 'high'
  if (scores.riskAdjusted < 65) return 'medium'
  return 'low'
}

// ---------------------------------------------------------------------------
// Route generation
// ---------------------------------------------------------------------------

export function generateRoutes(
  state: MobilityState,
  _intent: Intent,
  asOfDate?: string | Date,
  simulationMode: boolean = false,
): Route[] {
  const routes: Route[] = []

  // Resolve the active policy snapshot for the requested date.
  // CRITICAL: by default, simulated snapshots are EXCLUDED. Only explicit
  // simulation mode (admin/dev historical exploration) can access them.
  const snapshot = getPolicySnapshot('global', asOfDate ?? new Date(), simulationMode)
  const snapshotId = snapshot.id

  for (const pathway of PATHWAYS) {
    // If a non-current snapshot is requested, swap in superseded requirements
    // (e.g. the 2026 Blue Card salary threshold). For the current snapshot,
    // this returns the pathway's original requirements unchanged.
    const effectivePathway = applySnapshotToPathway(pathway, snapshotId)
    const eligibility = evaluatePathway(state, effectivePathway)
    const { steps, totalMonths, thirdPartyDependencies, reversible, futureOptions } = buildSteps(effectivePathway, eligibility)
    const scores = scoreRoute(state, _intent, effectivePathway, eligibility, totalMonths, thirdPartyDependencies, reversible)
    const dest = getCountry(effectivePathway.countryCode)

    routes.push({
      id: `route-${effectivePathway.id}`,
      label: `${dest?.name ?? effectivePathway.countryName} · ${effectivePathway.name}`,
      countryCode: effectivePathway.countryCode as CountryCode,
      countryName: effectivePathway.countryName,
      entryPathwayId: effectivePathway.id,
      steps,
      eligibility,
      scores,
      paretoOptimal: false, // set by frontier
      totalMonths,
      totalCostUSD: effectivePathway.estimatedCostUSD,
      thirdPartyDependencies,
      reversible,
      futureOptions,
      risk: riskBand(scores, eligibility),
      evidenceIds: eligibility.evidenceIds,
    })
  }

  return routes
}

/** Swap a legacy pathway's requirements for their snapshot-appropriate versions.
 *  For the current snapshot (snap-2024-11) this is a no-op. For snap-2026-01
 *  it replaces superseded requirements (e.g. the Blue Card salary threshold)
 *  and suspends programs whose v2 status is 'suspended' (CA SUV). */
function applySnapshotToPathway(pathway: Pathway, snapshotId: string): Pathway {
  if (snapshotId === 'snap-2024-11') return pathway // current — no change

  // Resolve normalized requirements for this pathway under the requested snapshot
  const normalizedReqs = getNormalizedRequirementsForPathway(pathway.id, snapshotId)
  if (normalizedReqs.length === 0) return pathway

  // Map normalized requirements back to legacy Requirement shape for the engine
  const swappedRequirements: Requirement[] = normalizedReqs.map((nr: NormalizedRequirement) => {
    // Reuse the existing legacy requirement if its kind+label match (unchanged reqs)
    const existing = pathway.requirements.find(
      (r) => r.kind === nr.kind && r.label.replace(/ ≥ .*$/, '').trim() === nr.label.replace(/ ≥ .*$/, '').trim(),
    )
    if (existing && JSON.stringify(existing.params) === JSON.stringify(nr.params)) {
      return existing
    }
    // Build a new legacy requirement from the normalized one
    return {
      id: nr.id,
      label: nr.label,
      kind: nr.kind,
      params: nr.params,
      evidenceIds: nr.evidenceIds,
      enablerAddressable: nr.enablerAddressable,
      criticality: nr.criticality,
    }
  })

  // Check if the program is suspended in the target snapshot
  const v2Program = PROGRAMS_V2[pathway.id]
  const suspended = v2Program?.status === 'suspended'

  return {
    ...pathway,
    id: suspended ? pathway.id : pathway.id, // keep id stable for route matching
    requirements: swappedRequirements,
    riskNotes: suspended
      ? `SUSPENDED under snapshot ${snapshotId}: ${v2Program?.riskNotes ?? ''}`
      : pathway.riskNotes,
  }
}

// Lookup of v2 program status by legacy pathway id
const PROGRAMS_V2: Record<string, { status: string; riskNotes?: string } | undefined> = {
  'ca-startup-visa': { status: 'suspended', riskNotes: 'Program suspended (projected IRCC intake cap).' },
  'de-blue-card': { status: 'active', riskNotes: 'Salary threshold raised per projected annual indexation.' },
  'pt-d7': { status: 'active', riskNotes: 'Minimum income raised to track the 2025 Portuguese minimum wage.' },
}

/** Composite utility under the user's weighted priorities (used for ranking,
 *  NOT for collapsing the frontier). */
export function compositeUtility(scores: RouteScores, intent: Intent): number {
  const w = (kind: Intent['priorities'][number]['kind']): number =>
    intent.priorities.find((p) => p.kind === kind)?.weight ?? 0.1
  const s = scores
  return (
    w('income_priority') * s.economicUpside +
    w('mobility_priority') * s.mobilityUpside +
    w('citizenship_priority') * s.citizenshipProspect +
    w('safety_priority') * s.riskAdjusted +
    w('family_stability') * s.familyUtility +
    w('entrepreneurship') * s.optionality +
    w('education_value') * s.longTermResidence +
    0.08 * s.immigrationProbability +
    0.06 * s.affordability +
    0.05 * s.speed
  )
}

export { POLICY_VERSION, getPathway }
