// Wayfinder Route Engine
//
// A route is a sequence of legal state transitions: CURRENT STATE → entry
// status → PR → citizenship. Routes are generated by deterministic graph
// search over the curated pathways + their downstream transitions. The LLM
// never invents route sequences; it only explains the ones produced here.

import type {
  CountryCode,
  Intent,
  MobilityState,
  Pathway,
  Route,
  RouteScores,
  RouteStep,
} from '@/lib/domain/types'
import { PATHWAYS, getPathway } from '@/lib/knowledge/pathways'
import { getCountry } from '@/lib/knowledge/countries'
import { evaluatePathway, isShortage } from './policy'
import { POLICY_VERSION } from '@/lib/knowledge/policy-version'

// ---------------------------------------------------------------------------
// Step construction
// ---------------------------------------------------------------------------

function buildSteps(pathway: Pathway, eligibility: ReturnType<typeof evaluatePathway>): {
  steps: RouteStep[]
  totalMonths: number
  thirdPartyDependencies: number
  reversible: boolean
  futureOptions: string[]
} {
  const steps: RouteStep[] = []
  const blockedSet = new Set(eligibility.blockers.map((b) => b.requirementId))

  // Step 0: current state
  steps.push({
    order: 0,
    status: 'Current state',
    description: `Apply for ${pathway.name} from your current country.`,
    durationMonths: pathway.processingTimeMonths,
    conditions: pathway.requirements.map((r) => r.label),
    evidenceIds: pathway.evidenceIds,
    blocked: false,
  })

  // Step 1: entry status (the pathway itself)
  const entryBlockers = pathway.requirements.filter((r) => blockedSet.has(r.id))
  steps.push({
    order: 1,
    status: pathway.name,
    description: pathway.tagline,
    durationMonths: pathway.validityMonths || pathway.processingTimeMonths,
    conditions: pathway.requirements.map((r) => r.label),
    evidenceIds: pathway.evidenceIds,
    blocked: entryBlockers.length > 0,
    blockerLabels: entryBlockers.map((r) => r.label),
  })

  // Downstream transitions
  let totalMonths = pathway.processingTimeMonths
  let reversible = pathway.downstream.every((t) => t.reversible) || pathway.downstream.length === 0
  const futureOptions: string[] = []

  pathway.downstream.forEach((t, i) => {
    steps.push({
      order: 2 + i,
      status: t.to,
      description: `${t.from} → ${t.to}`,
      durationMonths: t.durationMonths,
      conditions: t.conditions,
      evidenceIds: t.evidenceIds,
      blocked: false,
    })
    totalMonths += t.durationMonths
    if (!t.reversible) reversible = false
    futureOptions.push(t.to)
  })

  const thirdPartyDependencies = pathway.requiresThirdParty ? 1 : 0

  return { steps, totalMonths, thirdPartyDependencies, reversible, futureOptions }
}

// ---------------------------------------------------------------------------
// Scoring — multi-dimensional, never collapsed to one number for the frontier
// ---------------------------------------------------------------------------

const COUNTRY_INCOME_INDEX: Record<string, number> = {
  DE: 88, CA: 85, UK: 86, AE: 90, PT: 62, EE: 70, KE: 45,
}

function clamp(n: number, lo = 0, hi = 100) {
  return Math.max(lo, Math.min(hi, Math.round(n)))
}

function scoreRoute(
  state: MobilityState,
  intent: Intent,
  pathway: Pathway,
  eligibility: ReturnType<typeof evaluatePathway>,
  totalMonths: number,
  thirdPartyDependencies: number,
  reversible: boolean,
): RouteScores {
  const dest = getCountry(pathway.countryCode)
  const origin = getCountry(state.currentCountry.value) ?? getCountry('KE')!
  const curIncome = state.annualIncomeUSD.value ?? 40000

  // economicUpside: destination earning index vs current income
  const destIncomeIdx = COUNTRY_INCOME_INDEX[pathway.countryCode] ?? 60
  const incomeMultiple = destIncomeIdx / (COUNTRY_INCOME_INDEX[state.currentCountry.value] ?? 50)
  const economicUpside = clamp((incomeMultiple - 1) * 80 + 30 + (pathway.countryCode === 'AE' ? 12 : 0))

  // immigrationProbability: from eligibility status + dependency count + unknowns
  let prob = 75
  if (eligibility.status === 'eligible') prob = 88
  else if (eligibility.status === 'conditional') prob = 58 - eligibility.unknown.length * 6
  else prob = 18
  prob -= thirdPartyDependencies * 8
  prob -= eligibility.blockers.length * 3
  if (pathway.shortageOccupationFriendly && isShortage(state.occupationCategory.value, pathway.countryCode)) prob += 6
  const immigrationProbability = clamp(prob)

  // speed: inverse of months to PR-equivalent (cap 120 months)
  const prMonths = pathway.downstream.find((t) => /permanent|Settlement|ILR/i.test(t.to))?.durationMonths
  const monthsToDest = (prMonths ?? totalMonths) + pathway.processingTimeMonths
  const speed = clamp(100 - (monthsToDest / 120) * 100)

  // affordability: inverse of cost + capital required
  const cost = pathway.estimatedCostUSD
  const fundsReq = (pathway.requirements.find((r) => r.kind === 'min_savings_usd' || r.kind === 'settlement_funds_usd')?.params as any)?.amount ?? 0
  const totalBurden = cost + fundsReq * 0.15
  const affordability = clamp(100 - (totalBurden / 30000) * 100)

  // longTermResidence: leads to PR?
  const hasPR = pathway.downstream.some((t) => /permanent|Settlement|ILR/i.test(t.to))
  const longTermResidence = clamp(hasPR ? 88 : 35)

  // citizenshipProspect
  const hasCit = pathway.downstream.some((t) => /citizenship/i.test(t.to))
  let cit = hasCit ? 70 : 10
  if (dest?.dualCitizenship === 'permitted') cit += 12
  else if (dest?.dualCitizenship === 'restricted') cit -= 8
  else if (dest?.dualCitizenship === 'prohibited') cit -= 25
  // faster citizenship = higher
  const citMonths = pathway.downstream.find((t) => /citizenship/i.test(t.to))?.durationMonths ?? 999
  cit += clamp(20 - citMonths / 12, -10, 20)
  const citizenshipProspect = clamp(cit)

  // familyUtility
  const family = (state.hasSpouse.value === true || state.hasChildren.value === true)
  let fam = pathway.countryCode === 'CA' ? 90 : pathway.countryCode === 'PT' ? 80 : pathway.countryCode === 'DE' ? 78 : 60
  if (!family) fam = Math.min(100, fam + 8)
  const familyUtility = clamp(fam)

  // mobilityUpside: passport strength gained
  const originScore = origin.passportMobilityScore
  const destScore = dest?.passportMobilityScore ?? 70
  const mobilityUpside = clamp(((destScore - originScore) / 60) * 100 + 20)

  // optionality: future doors = downstream count + dual citizenship + EU access
  let opt = pathway.downstream.length * 12
  if (dest?.region === 'EU' || dest?.region === 'EEA') opt += 18
  if (dest?.dualCitizenship === 'permitted') opt += 10
  const optionality = clamp(opt)

  // reversibility
  const reversibility = clamp(reversible ? 80 : 30)

  // risk band
  let riskScore = 60
  if (eligibility.status === 'eligible') riskScore += 20
  else if (eligibility.status === 'ineligible') riskScore -= 35
  riskScore -= thirdPartyDependencies * 6
  riskScore -= eligibility.blockers.length * 2
  if (pathway.riskNotes?.match(/long|backlog|competitive/i)) riskScore -= 8
  const riskAdjusted = clamp(riskScore)

  return {
    economicUpside,
    immigrationProbability,
    speed,
    affordability,
    longTermResidence,
    citizenshipProspect,
    familyUtility,
    mobilityUpside,
    optionality,
    reversibility,
    riskAdjusted,
  }
}

function riskBand(scores: RouteScores, eligibility: ReturnType<typeof evaluatePathway>): Route['risk'] {
  if (eligibility.status === 'ineligible') return 'high'
  if (scores.riskAdjusted < 45) return 'high'
  if (scores.riskAdjusted < 65) return 'medium'
  return 'low'
}

// ---------------------------------------------------------------------------
// Route generation
// ---------------------------------------------------------------------------

export function generateRoutes(state: MobilityState, _intent: Intent): Route[] {
  const routes: Route[] = []

  for (const pathway of PATHWAYS) {
    const eligibility = evaluatePathway(state, pathway)
    const { steps, totalMonths, thirdPartyDependencies, reversible, futureOptions } = buildSteps(pathway, eligibility)
    const scores = scoreRoute(state, _intent, pathway, eligibility, totalMonths, thirdPartyDependencies, reversible)
    const dest = getCountry(pathway.countryCode)

    routes.push({
      id: `route-${pathway.id}`,
      label: `${dest?.name ?? pathway.countryName} · ${pathway.name}`,
      countryCode: pathway.countryCode as CountryCode,
      countryName: pathway.countryName,
      entryPathwayId: pathway.id,
      steps,
      eligibility,
      scores,
      paretoOptimal: false, // set by frontier
      totalMonths,
      totalCostUSD: pathway.estimatedCostUSD,
      thirdPartyDependencies,
      reversible,
      futureOptions,
      risk: riskBand(scores, eligibility),
      evidenceIds: eligibility.evidenceIds,
    })
  }

  return routes
}

/** Composite utility under the user's weighted priorities (used for ranking,
 *  NOT for collapsing the frontier). */
export function compositeUtility(scores: RouteScores, intent: Intent): number {
  const w = (kind: Intent['priorities'][number]['kind']): number =>
    intent.priorities.find((p) => p.kind === kind)?.weight ?? 0.1
  const s = scores
  return (
    w('income_priority') * s.economicUpside +
    w('mobility_priority') * s.mobilityUpside +
    w('citizenship_priority') * s.citizenshipProspect +
    w('safety_priority') * s.riskAdjusted +
    w('family_stability') * s.familyUtility +
    w('entrepreneurship') * s.optionality +
    w('education_value') * s.longTermResidence +
    0.08 * s.immigrationProbability +
    0.06 * s.affordability +
    0.05 * s.speed
  )
}

export { POLICY_VERSION, getPathway }
